version: '3.4'

services:
  gp2gp:
    image: nhsdev/nia-gp2gp-adaptor:1.5.0
    networks:
      - commonforgp2gp
    build:
      context: ../..
      dockerfile: docker/service/Dockerfile
    depends_on:
      - mongodb
    #  - activemq
    ports:
      - "8080:8080"
    environment:
      - GP2GP_SERVER_PORT
      - GP2GP_LOGGING_LEVEL
      - GP2GP_AMQP_BROKERS
      - GP2GP_AMQP_USERNAME
      - GP2GP_AMQP_PASSWORD
      - GP2GP_AMQP_MAX_REDELIVERIES
      - GP2GP_MONGO_URI
      - GP2GP_MONGO_DATABASE_NAME
      - GP2GP_MONGO_TTL
      - GP2GP_COSMOS_DB_ENABLED
      - GP2GP_STORAGE_TYPE
      - GP2GP_STORAGE_CONTAINER_NAME
      - GP2GP_MHS_OUTBOUND_URL
      - AZURE_STORAGE_CONNECTION_STRING
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - GP2GP_GPC_GET_URL
      - GP2GP_GPC_DOCUMENTS_FHIR_BASE
      - GP2GP_GPC_STRUCTURED_FHIR_BASE
      - GP2GP_SSL_TRUST_STORE_URL
      - GP2GP_SSL_TRUST_STORE_PASSWORD
      - GP2GP_GPC_OVERRIDE_NHS_NUMBER
      - GP2GP_GPC_OVERRIDE_FROM_ASID
      - GP2GP_GPC_OVERRIDE_TO_ASID
      - GP2GP_GPC_GET_TEST_URL
      - GP2GP_LARGE_ATTACHMENT_THRESHOLD
      - GP2GP_LARGE_EHR_EXTRACT_THRESHOLD

  mongodb:
    networks:
      - commonforgp2gp
    image: bitnami/mongodb
    ports:
      - "27017:27017"

  gpcc:
    image: nhsdev/nia-gpc-consumer-adaptor:0.3.3
    networks:
      - commonforgp2gp
    ports:
      - "8090:8090"
    environment:
      - GPC_CONSUMER_LOGGING_LEVEL
      - GPC_CONSUMER_SERVER_PORT
      - GPC_CONSUMER_SPINE_CLIENT_CERT
      - GPC_CONSUMER_SPINE_CLIENT_KEY
      - GPC_CONSUMER_SPINE_ROOT_CA_CERT
      - GPC_CONSUMER_SPINE_SUB_CA_CERT
      - GPC_CONSUMER_SEARCH_DOCUMENTS_PATH
      - GPC_CONSUMER_GPC_STRUCTURED_PATH
      - GPC_CONSUMER_GPC_GET_PATIENT_PATH
      - GPC_CONSUMER_GPC_GET_DOCUMENT_PATH
      - GPC_CONSUMER_SDS_URL
      - GPC_CONSUMER_SDS_APIKEY

  activemq:
    networks:
      - commonforgp2gp
    build:
      context: activemq
    ports:
      - "8161:8161"
      - "5672:5672"

networks:
  commonforgp2gp:
    external: true
