#!/usr/bin/env bash

#global
export GPC_CONSUMER_LOGGING_LEVEL="DEBUG"

#gp2gp
export GP2GP_SERVER_PORT="8080"
export GP2GP_LOGGING_LEVEL=DEBUG
export GP2GP_AMQP_BROKERS="amqp://activemq:5672"
export GP2GP_MONGO_URI="mongodb://mongodb:27017"
export GP2GP_MONGO_DATABASE_NAME="gp2gp"
export GP2GP_MHS_OUTBOUND_URL="FILL IN"
export GP2GP_GPC_GET_URL="http://gpcc:8090/@ODS_CODE@/STU3/1/gpconnect"


#gpcc
export GPC_CONSUMER_SERVER_PORT="8090"
export GPC_CONSUMER_SDS_APIKEY="anykey"

#they are also needed

#GP2GP
    #export GP2GP_AMQP_USERNAME=
    #export GP2GP_AMQP_PASSWORD=

  #STORAGE
    #export GP2GP_STORAGE_TYPE=
    #export GP2GP_STORAGE_CONTAINER_NAME=
  #AZURE
    #export AZURE_STORAGE_CONNECTION_STRING=

  #AWS
    #export AWS_ACCESS_KEY_ID=
    #export AWS_SECRET_ACCESS_KEY=
    #export AWS_REGION=

  #SSL
    #export GP2GP_SSL_TRUST_STORE_URL=
    #export GP2GP_SSL_TRUST_STORE_PASSWORD=

    #export GP2GP_AMQP_MAX_REDELIVERIES=
    #export GP2GP_MONGO_TTL=
    #export GP2GP_COSMOS_DB_ENABLED=
    #export GP2GP_GPC_DOCUMENTS_FHIR_BASE=
    #export GP2GP_GPC_STRUCTURED_FHIR_BASE=
    #export GP2GP_GPC_OVERRIDE_NHS_NUMBER=
    #export GP2GP_GPC_OVERRIDE_FROM_ASID=
    #export GP2GP_GPC_OVERRIDE_TO_ASID=
    #export GP2GP_GPC_GET_TEST_URL=
    #export GP2GP_LARGE_ATTACHMENT_THRESHOLD=
    #export GP2GP_LARGE_EHR_EXTRACT_THRESHOLD=

#GPCC

    #export GPC_CONSUMER_SPINE_CLIENT_CERT=
    #export GPC_CONSUMER_SPINE_CLIENT_KEY=
    #export GPC_CONSUMER_SPINE_ROOT_CA_CERT=
    #export GPC_CONSUMER_SPINE_SUB_CA_CERT=

    #export GPC_CONSUMER_SEARCH_DOCUMENTS_PATH=
    #export GPC_CONSUMER_GPC_STRUCTURED_PATH=
    #export GPC_CONSUMER_GPC_GET_PATIENT_PATH=
    #export GPC_CONSUMER_GPC_GET_DOCUMENT_PATH=
    #export GPC_CONSUMER_SDS_URL=

